name: Update Version

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun run scripts/index.ts

      - run: |
          version=$(bun run scripts/index.ts)
          echo "version=$version" >> $GITHUB_ENV"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.version }}"
          prerelease: false
          title: "${{ env.version }}"
